version: "2"

services:
  rabbitmq:
    image: "rabbitmq"
    hostname: "rabbitmq"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    networks:
      - task1

  producer:
    build: producer
    networks:
      - task1

  consumer:
    build: consumer
    networks:
      - task1

networks:
  task1:
driver: bridge
